# Generated by Django 6.0.2 on 2026-03-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_decription_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='amount_cart',
            new_name='quantity',
        ),
    ]
