# Generated by Django 6.0.2 on 2026-04-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_amount_cart_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=100, help_text='Чем меньше число, тем выше в списке'),
        ),
    ]
