# Generated by Django 6.0.2 on 2026-05-28 07:57

from django.db import migrations


def create_profiles(apps, schema_editor):
    User = apps.get_model("users", "User")
    Profile = apps.get_model("users", "Profile")
    for user in User.objects.all():
        role = "ADMIN" if (user.is_staff or user.is_superuser) else "CUSTOMER"
        Profile.objects.get_or_create(user=user, defaults={"role": role})


def remove_profiles(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    Profile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.RunPython(create_profiles, remove_profiles),
    ]
